"use client";
import { useEffect, useRef, useState } from "react";
import { Mic, Square, ArrowRight, ArrowLeft, ShieldCheck, Flame, Fingerprint, FolderOpen, Utensils, HeartHandshake, Volume2, RotateCcw, ExternalLink, Send, Check, X, Keyboard, LoaderCircle } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { NativeSelect, NativeSelectOption } from "@/components/ui/native-select";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription, DialogFooter } from "@/components/ui/dialog";
import { GUIDES, SOURCES, ACTIONS, getGuide, type Language } from "@/lib/guides";
import { privacyReason, safeAuditText, type Decision } from "@/lib/agent";
const icons:Record<string,typeof Flame>={lpg:Flame,aadhaar:Fingerprint,digilocker:FolderOpen,pension:HeartHandshake,'lemon-rice':Utensils};
type SpeechEvent={results:{[key:number]:{[key:number]:{transcript:string}}}};
type Recognizer={lang:string;continuous:boolean;interimResults:boolean;onresult:((e:SpeechEvent)=>void)|null;onerror:((e:{error:string})=>void)|null;onend:(()=>void)|null;start:()=>void;stop:()=>void};
type SpeechWindow=Window & {SpeechRecognition?:new()=>Recognizer;webkitSpeechRecognition?:new()=>Recognizer};
const copy={te:{greeting:'ఏం చేయాలో',together:'కలిసి తెలుసుకుందాం.',sub:'మీ ప్రశ్న చెప్పండి. ఒక్కో అడుగు సులభంగా తెలుసుకోండి.',speak:'మాట్లాడండి',stop:'ఆపండి',choose:'దేనిలో సహాయం కావాలి?',type:'టైప్ చేయవచ్చు',placeholder:'ఉదా: నా గ్యాస్‌కు ఆధార్ KYC ఎలా చేయాలి?',ask:'అడగండి',listen:'వినండి',repeat:'మళ్లీ వినండి',next:'తర్వాతి అడుగు',back:'వెనుకకు',source:'ఈ సమాచారానికి ఆధారం',privacy:'ఆధార్ నంబర్, OTP లేదా PIN ఇక్కడ చెప్పవద్దు.',new:'కొత్త ప్రశ్న',heard:'మీ ప్రశ్న ఇలా వినిపించింది',confirm:'ఇదే నా ప్రశ్న',empty:'ఒక పని ఎంచుకోండి లేదా మాట్లాడండి',emptysub:'విధానం, ఆధారం, అధికారిక సేవకు లింక్ — ఒకేచోట.',step:'అడుగు',of:'/',ready:'సిద్ధంగా ఉన్న మార్గదర్శకాలు',review:'చివరిగా చూసిన తేదీ',notice:'పని చేయడానికి సహాయం. అధికారిక సేవకు ప్రత్యామ్నాయం కాదు.',voiceTitle:'మాట్లాడే ముందు',voiceBody:'మీ మాటలు టెక్స్ట్‌గా మార్చడానికి వాయిస్ సేవకు వెళ్తాయి. ఆధార్ నంబర్, OTP లేదా PIN చెప్పవద్దు. రికార్డింగ్ ఈ యాప్‌లో నిల్వ చేయము.',proceed:'సరే, మాట్లాడతాను',cancel:'వద్దు',open:'అధికారిక సైట్‌కు వెళ్తున్నారు',openBody:'ఆ సైట్‌లోనే అవసరమైన వివరాలు నమోదు చేయండి. తిరిగి తోడుకు వచ్చి తర్వాతి అడుగు చూడవచ్చు.',finish:'విధానం చూశారు',finishBody:'ఇది మార్గదర్శకం మాత్రమే. అధికారిక పని పూర్తయిందని నిర్ధారణ కాదు.',readAll:'అన్ని అడుగులు చూడండి',close:'మూసివేయండి'},en:{greeting:'A little help.',together:'One step at a time.',sub:'Ask in your own words. Find a clear next step.',speak:'Speak your question',stop:'Stop recording',choose:'What would you like help with?',type:'Or type a question',placeholder:'Example: How do I do Aadhaar KYC for my gas connection?',ask:'Ask Thodu',listen:'Listen',repeat:'Listen again',next:'Next step',back:'Back',source:'Where this information comes from',privacy:'Keep Aadhaar numbers, OTPs and PINs out of this chat.',new:'New question',heard:'Here is what I heard',confirm:'Use this question',empty:'Choose a task or ask a question',emptysub:'Clear steps, sources and a link to the official service.',step:'STEP',of:'OF',ready:'Available guides',review:'Last reviewed',notice:'Independent guidance. Not a government service.',voiceTitle:'Before you speak',voiceBody:'Your audio is sent to a speech service for transcription. Do not say Aadhaar numbers, OTPs or PINs. This app does not store your recording.',proceed:'Continue and speak',cancel:'Cancel',open:'You are leaving Thodu',openBody:'Enter any required private details only on the official service. You can return to Thodu for the next step.',finish:'You have seen the steps',finishBody:'This is guidance, not confirmation that your official task is complete.',readAll:'View all steps',close:'Close'}};
export default function Home(){
 const [lang,setLang]=useState<Language>('te'),[draft,setDraft]=useState(''),[decision,setDecision]=useState<Decision|null>(null),[question,setQuestion]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[recording,setRecording]=useState(false),[transcript,setTranscript]=useState(''),[speaking,setSpeaking]=useState(false),[voiceConsent,setVoiceConsent]=useState(false),[acceptedVoice,setAcceptedVoice]=useState(false),[external,setExternal]=useState(''),[allSteps,setAllSteps]=useState(false),[showTyping,setShowTyping]=useState(false),[status,setStatus]=useState({modelReady:false,transcriptionReady:false,speechReady:false});
 const rec=useRef<Recognizer|null>(null),media=useRef<MediaRecorder|null>(null),stream=useRef<MediaStream|null>(null),audio=useRef<HTMLAudioElement|null>(null),recordTimer=useRef<ReturnType<typeof setTimeout>|null>(null),epoch=useRef(0),answerRef=useRef<HTMLElement|null>(null);
 const c=copy[lang],guide=getGuide(decision?.guideId||''),step=decision?.step||0;
 useEffect(()=>{fetch('/api/status').then(r=>r.json() as Promise<{modelReady:boolean;transcriptionReady:boolean;speechReady:boolean}>).then(setStatus).catch(()=>{});return()=>{rec.current?.stop();media.current?.state==='recording'&&media.current.stop();stream.current?.getTracks().forEach(t=>t.stop());if(recordTimer.current)clearTimeout(recordTimer.current);window.speechSynthesis?.cancel();audio.current?.pause();};},[]);
 function stopSpeech(){epoch.current++;window.speechSynthesis?.cancel();audio.current?.pause();setSpeaking(false);}
 async function ask(text:string){if(busy||!text.trim())return;stopSpeech();setError('');setQuestion(safeAuditText(text));setTranscript('');setDraft('');
  if(privacyReason(text)){setDecision({kind:'blocked',message:c.privacy,reason:'client-privacy',engine:'rules'});return;}
  setBusy(true);try{const r=await fetch('/api/ask',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:text,language:lang,...(guide?{guideId:guide.id,step}:{})})});const data=await r.json() as Decision & {error?:string};if(!r.ok)throw Error(data.error||'Request failed');setDecision(data);setAllSteps(false);setTimeout(()=>answerRef.current?.scrollIntoView({behavior:'smooth',block:'nearest'}),50);}catch{setError(lang==='te'?'ప్రస్తుతం సమాధానం రాలేదు. కింద ఒక పని ఎంచుకుని ప్రయత్నించండి.':'Could not get an answer. Please try again or select a task.');}finally{setBusy(false);}}
 function selectGuide(id:string){stopSpeech();const g=getGuide(id);if(!g)return;setError('');setQuestion(g.title[lang]);setDecision({kind:'guide',guideId:id,step:0,message:g.summary[lang],reason:'selected-guide',engine:'rules'});setAllSteps(false);}
 function move(n:number){if(!guide)return;stopSpeech();setDecision(d=>d?{...d,step:Math.max(0,Math.min(guide.steps.length-1,n))}:d);}
 async function speak(){if(!guide)return;if(speaking){stopSpeech();return;}setError('');const n=++epoch.current;
  if(status.speechReady){setSpeaking(true);try{const r=await fetch('/api/speak',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({guideId:guide.id,step,language:lang})});if(!r.ok)throw Error();const url=URL.createObjectURL(await r.blob());if(epoch.current!==n){URL.revokeObjectURL(url);return;}audio.current=new Audio(url);audio.current.onended=()=>{setSpeaking(false);URL.revokeObjectURL(url);};audio.current.onerror=()=>{setSpeaking(false);URL.revokeObjectURL(url);};await audio.current.play();return;}catch{setSpeaking(false);}}
  const synth=window.speechSynthesis;if(!synth){setError(lang==='te'?'ఈ పరికరంలో వినిపించే సదుపాయం లేదు.':'Speech playback is unavailable on this device.');return;}
  const voice=synth.getVoices().find(v=>v.lang.toLowerCase().startsWith(lang));if(!voice&&lang==='te'){setError('ఈ పరికరంలో తెలుగు వాయిస్ అందుబాటులో లేదు. తెలుగు వాయిస్ ఉన్న పరికరం ఉపయోగించండి లేదా అడుగులు చదవండి.');return;}
  const u=new SpeechSynthesisUtterance(guide.steps[step][lang]);u.lang=lang==='te'?'te-IN':'en-IN';if(voice)u.voice=voice;u.rate=.85;u.onend=()=>setSpeaking(false);u.onerror=()=>setSpeaking(false);setSpeaking(true);synth.speak(u);
 }
 function handleTranscript(text:string){if(privacyReason(text)){setError(c.privacy);setTranscript('');return;}setTranscript(text);}
 function stopRecording(){rec.current?.stop();if(media.current?.state==='recording')media.current.stop();stream.current?.getTracks().forEach(t=>t.stop());if(recordTimer.current)clearTimeout(recordTimer.current);setRecording(false);}
 async function beginRecording(){setVoiceConsent(false);setAcceptedVoice(true);stopSpeech();setError('');setTranscript('');
  if(status.transcriptionReady&&navigator.mediaDevices?.getUserMedia){try{stream.current=await navigator.mediaDevices.getUserMedia({audio:true});media.current=new MediaRecorder(stream.current);const chunks:BlobPart[]=[];media.current.ondataavailable=e=>chunks.push(e.data);media.current.onstop=async()=>{stream.current?.getTracks().forEach(t=>t.stop());setRecording(false);setBusy(true);try{const blob=new Blob(chunks,{type:media.current?.mimeType||'audio/webm'});const fd=new FormData();fd.append('audio',blob,'question.webm');fd.append('language',lang);const r=await fetch('/api/transcribe',{method:'POST',body:fd});const d=await r.json() as {text:string;error?:string};if(!r.ok)throw Error(d.error);handleTranscript(d.text);}catch{setError(lang==='te'?'వినిపించలేదు. మళ్లీ ప్రయత్నించండి లేదా ఒక పని ఎంచుకోండి.':'Could not transcribe. Try again or select a task.');}finally{setBusy(false);}};media.current.start();setRecording(true);recordTimer.current=setTimeout(stopRecording,25000);return;}catch{setError(lang==='te'?'మైక్రోఫోన్ అనుమతి రాలేదు. ఒక పని ఎంచుకుని కొనసాగండి.':'Microphone access was unavailable. You can select a task instead.');return;}}
  const w=window as SpeechWindow;const Recognition=w.SpeechRecognition||w.webkitSpeechRecognition;if(!Recognition){setError(lang==='te'?'ఈ బ్రౌజర్‌లో మాటలు గుర్తించే సదుపాయం లేదు. మరో బ్రౌజర్ లేదా కింద పనుల ఎంపిక ఉపయోగించండి.':'Speech recognition is unavailable in this browser. Use another browser or select a task below.');return;}
  const r=new Recognition();rec.current=r;r.lang=lang==='te'?'te-IN':'en-IN';r.continuous=false;r.interimResults=false;r.onresult=e=>handleTranscript(e.results[0][0].transcript);r.onerror=()=>{setRecording(false);setError(lang==='te'?'వినిపించలేదు లేదా మైక్రోఫోన్ అనుమతి రాలేదు. మళ్లీ ప్రయత్నించండి.':'Could not hear you or microphone access was denied. Please try again.');};r.onend=()=>setRecording(false);try{r.start();setRecording(true);}catch{setError('Microphone unavailable.');}
 }
 function mic(){if(recording){stopRecording();return;}if(!acceptedVoice)setVoiceConsent(true);else void beginRecording();}
 function reset(){stopRecording();stopSpeech();setDecision(null);setQuestion('');setError('');setTranscript('');setDraft('');}
 useEffect(()=>{const ctx=(document as Document&{modelContext?:{registerTool:(t:unknown,o:unknown)=>Promise<void>}}).modelContext;if(!ctx)return;const life=new AbortController();Promise.resolve(ctx.registerTool({name:'start_thodu_guide',title:'Start an everyday task guide',description:'Open a source-backed guide in the visible interface. Does not complete any official task.',inputSchema:{type:'object',properties:{guideId:{type:'string',enum:GUIDES.map(g=>g.id)}},required:['guideId'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:async(input:unknown)=>{const i=input as {guideId?:unknown};if(!i||Object.keys(i).length!==1||typeof i.guideId!=='string'||!getGuide(i.guideId))throw Error('Choose an available guide.');selectGuide(i.guideId);await new Promise<void>(resolve=>requestAnimationFrame(()=>requestAnimationFrame(()=>resolve())));return {started:i.guideId,officialTaskCompleted:false};}},{signal:life.signal})).catch(()=>{});return()=>life.abort();},[lang]);
 return <main className="thodu-shell"><header className="topbar"><a className="brand" href="/">తోడు <span>THODU</span></a><div className="header-actions"><NativeSelect aria-label="Language" value={lang} onChange={e=>{stopRecording();stopSpeech();setLang(e.target.value as Language);setError('');setTranscript('');if(decision?.kind!=='guide')setDecision(null);}}><NativeSelectOption value="te">తెలుగు</NativeSelectOption><NativeSelectOption value="en">English</NativeSelectOption></NativeSelect><Button variant="ghost" onClick={reset} className="reset-button" disabled={busy}><RotateCcw/>{c.new}</Button></div></header>
 <div className="workspace"><aside className="ask-side"><section className="intro"><p className="eyebrow">{lang==='te'?'మీ రోజువారీ పనుల్లో మీకు తోడు':'YOUR EVERYDAY COMPANION'}</p><h1>{c.greeting}<br/><em>{c.together}</em></h1><p>{c.sub}</p><Button className={'voice-main '+(recording?'is-recording':'')} onClick={mic} disabled={busy}>{recording?<Square/>:<Mic/>}{recording?c.stop:c.speak}</Button><Button variant="ghost" className="type-toggle" onClick={()=>setShowTyping(v=>!v)}><Keyboard/>{c.type}</Button>
 {showTyping&&<form onSubmit={e=>{e.preventDefault();void ask(draft);}} className="ask-form"><Textarea aria-label={c.type} value={draft} onChange={e=>setDraft(e.target.value)} maxLength={1200} placeholder={c.placeholder}/><Button type="submit" disabled={busy||!draft.trim()}><Send/>{c.ask}</Button></form>}
 {transcript&&<div className="transcript"><p>{c.heard}</p><p className="transcript-text">{transcript}</p><div className="inline-actions"><Button onClick={()=>void ask(transcript)}><Check/>{c.confirm}</Button><Button variant="ghost" onClick={()=>setTranscript('')}><X/>{c.cancel}</Button></div></div>}
 {error&&<p className="error-message" role="alert">{error}</p>}
 </section><section className="topics"><h2>{c.choose}</h2><div className="topic-grid">{GUIDES.map(g=>{const Icon=icons[g.id];return <Button variant="outline" key={g.id} className={'topic-card '+(guide?.id===g.id?'selected':'')} onClick={()=>selectGuide(g.id)} disabled={busy}><Icon/><span>{g.title[lang]}</span><ArrowRight size={18}/></Button>;})}</div></section></aside>
 <section ref={answerRef} className={'answer-side '+(!decision?'empty-answer':'')} aria-live="polite" aria-busy={busy}>{busy?<div className="waiting"><LoaderCircle className="spin"/><p>{lang==='te'?'మీ ప్రశ్న చూస్తున్నాను…':'Looking at your question…'}</p></div>:guide?<><div className="answer-topline"><span>{guide.kind==='recipe'?(lang==='te'?'వంటింట్లో':'IN THE KITCHEN'):(lang==='te'?'మీ పని సులభంగా':'LET’S WORK THROUGH IT')}</span><Button variant="ghost" size="icon" aria-label={c.close} onClick={reset}><X/></Button></div><h2>{guide.title[lang]}</h2><p className="answer-summary">{guide.summary[lang]}</p><div className="step-track">{guide.steps.map((_,i)=><span className={i<=step?'done':''} key={i}/>)}</div><p className="step-label">{c.step} {step+1} {c.of} {guide.steps.length}</p><p className="step-text">{guide.steps[step][lang]}</p><Button variant="outline" className="listen-button" onClick={()=>void speak()}>{speaking?<Square/>:<Volume2/>}{speaking?c.stop:c.listen}</Button><div className="step-nav"><Button variant="ghost" disabled={step===0} onClick={()=>move(step-1)}><ArrowLeft/>{c.back}</Button>{step<guide.steps.length-1?<Button onClick={()=>move(step+1)}>{c.next}<ArrowRight/></Button>:<span className="completed"><Check/>{c.finish}</span>}</div>{step===guide.steps.length-1&&<p className="small-note">{c.finishBody}</p>}<Button variant="ghost" className="all-steps-toggle" onClick={()=>setAllSteps(v=>!v)}>{c.readAll}</Button>{allSteps&&<ol className="all-steps">{guide.steps.map((s,i)=><li key={i}>{s[lang]}</li>)}</ol>}
 <div className="guide-note"><ShieldCheck/><p>{guide.note[lang]}</p></div><Button className="official-button" variant="outline" onClick={()=>setExternal(ACTIONS[guide.actionId].url)}>{ACTIONS[guide.actionId].title[lang]}<ExternalLink/></Button><div className="sources"><h3>{c.source}</h3>{guide.sourceIds.map(id=><a key={id} href={SOURCES[id].url} target="_blank" rel="noopener noreferrer">{SOURCES[id].publisher}<ExternalLink size={14}/></a>)}<p>{c.review}: {guide.reviewed}</p></div></>:decision?<div className="boundary-answer"><ShieldCheck size={36}/><h2>{lang==='te'?'సురక్షితంగా ముందుకు వెళ్దాం':'Let’s take a safe next step'}</h2><p>{decision.message}</p><Button variant="outline" onClick={reset}>{c.new}</Button></div>:<><div className="empty-mark"><Mic size={48}/></div><h2>{c.empty}</h2><p>{c.emptysub}</p><div className="example-question"><span>{lang==='te'?'ఇలా అడగవచ్చు':'TRY ASKING'}</span><Button variant="ghost" onClick={()=>void ask(lang==='te'?'నా గ్యాస్‌కు ఆధార్ KYC ఎలా చేయాలి?':'How do I do Aadhaar KYC for my gas connection?')}>{lang==='te'?'“నా గ్యాస్‌కు ఆధార్ KYC ఎలా చేయాలి?”':'“How do I do Aadhaar KYC for my gas connection?”'}<ArrowRight/></Button></div></>}
 </section></div><footer><ShieldCheck size={20}/><span>{c.privacy}<br/><small>{c.notice}</small></span><a href="/evaluation">{lang==='te'?'ప్రాజెక్ట్ పరీక్షలు':'Project tests'}</a></footer>
 <Dialog open={voiceConsent} onOpenChange={setVoiceConsent}><DialogContent><DialogHeader><DialogTitle>{c.voiceTitle}</DialogTitle><DialogDescription>{c.voiceBody}</DialogDescription></DialogHeader><DialogFooter><Button variant="outline" onClick={()=>setVoiceConsent(false)}>{c.cancel}</Button><Button onClick={()=>void beginRecording()}>{c.proceed}</Button></DialogFooter></DialogContent></Dialog>
 <Dialog open={!!external} onOpenChange={v=>!v&&setExternal('')}><DialogContent><DialogHeader><DialogTitle>{c.open}</DialogTitle><DialogDescription>{c.openBody}</DialogDescription></DialogHeader><p className="external-host">{external?new URL(external).hostname:''}</p><DialogFooter><Button variant="outline" onClick={()=>setExternal('')}>{c.cancel}</Button><Button asChild><a href={external} target="_blank" rel="noopener noreferrer" onClick={()=>setExternal('')}>{lang==='te'?'సైట్ తెరవండి':'Open website'}<ExternalLink/></a></Button></DialogFooter></DialogContent></Dialog>
 </main>;
}
