"use client";
import { useEffect, useRef, useState } from "react";
import { Mic, Square, ArrowRight, ArrowLeft, ShieldCheck, Flame, Fingerprint, FolderOpen, Utensils, HeartHandshake, Volume2, RotateCcw, ExternalLink, Send, Check, X, Keyboard, LoaderCircle } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs";
import { Textarea } from "@/components/ui/textarea";
import { NativeSelect, NativeSelectOption } from "@/components/ui/native-select";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription, DialogFooter } from "@/components/ui/dialog";
import { GUIDES, SOURCES, ACTIONS, getGuide, type Language } from "@/lib/guides";
import { privacyReason, safeAuditText, type Decision } from "@/lib/agent";
const topicArt:Record<string,{emoji:string;tone:string;hint:{te:string;en:string}}>={
 lpg:{emoji:'🔥',tone:'peach',hint:{te:'అధికారిక మార్గం',en:'Official routes'}},
 'chicken-biryani':{emoji:'🍲',tone:'saffron',hint:{te:'వంటింట్లో కొత్త రుచి',en:'Something delicious'}},
 whatsapp:{emoji:'💬',tone:'mint',hint:{te:'ఫొటో పంచుకుందాం',en:'Share a little moment'}},
 kitchenware:{emoji:'🥘',tone:'blue',hint:{te:'మీ వంటింటికి',en:'For your kitchen'}},
 sarees:{emoji:'🥻',tone:'rose',hint:{te:'మీకు నచ్చిన శైలి',en:'Find your next favourite'}},
 schemes:{emoji:'🏛️',tone:'blue',hint:{te:'పథకాలు తెలుసుకుందాం',en:'Explore official information'}},
 'land-rights':{emoji:'⚖️',tone:'mint',hint:{te:'న్యాయ సహాయం వైపు',en:'Understand where to turn'}},
 ganesh:{emoji:'🪔',tone:'saffron',hint:{te:'కథ, సంప్రదాయం, చరిత్ర',en:'A story to discover'}},
 aadhaar:{emoji:'🪪',tone:'peach',hint:{te:'UIDAI సేవలు',en:'UIDAI services'}},
 digilocker:{emoji:'📂',tone:'blue',hint:{te:'పత్రాలకు దారి',en:'Find your documents'}},
 pension:{emoji:'🤝',tone:'mint',hint:{te:'Jeevan Pramaan',en:'Jeevan Pramaan'}},
 'lemon-rice':{emoji:'🍋',tone:'saffron',hint:{te:'సులభమైన వంటకం',en:'A familiar favourite'}},
 festivals:{emoji:'🎊',tone:'rose',hint:{te:'మరిన్ని సంప్రదాయాలు',en:'More celebrations'}}
};
const topicOrder=['lpg','chicken-biryani','whatsapp','kitchenware','sarees','schemes','land-rights','ganesh','aadhaar','digilocker','pension','lemon-rice','festivals'];
const groups=[{id:'all',en:'All topics',te:'అన్ని'},{id:'services',en:'Everyday help',te:'రోజువారీ సహాయం'},{id:'home',en:'Home & shopping',te:'ఇల్లు, షాపింగ్'},{id:'culture',en:'Stories & festivals',te:'కథలు, పండుగలు'}];
function groupOf(category:string){return ['kitchen','shopping'].includes(category)?'home':category==='culture'?'culture':'services';}
type SpeechEvent={results:{[key:number]:{[key:number]:{transcript:string}}}};
type Recognizer={lang:string;continuous:boolean;interimResults:boolean;onresult:((e:SpeechEvent)=>void)|null;onerror:((e:{error:string})=>void)|null;onend:(()=>void)|null;start:()=>void;stop:()=>void};
type SpeechWindow=Window & {SpeechRecognition?:new()=>Recognizer;webkitSpeechRecognition?:new()=>Recognizer};
const copy={te:{greeting:'మీ మాటతో,',together:'మీ ముందడుగు.',sub:'మీ ప్రశ్న చెప్పండి. ఒక్కో అడుగు సులభంగా తెలుసుకోండి.',speak:'మాట్లాడండి',stop:'ఆపండి',choose:'దేనిలో సహాయం కావాలి?',type:'టైప్ చేయవచ్చు',placeholder:'ఉదా: నా గ్యాస్‌కు ఆధార్ KYC ఎలా చేయాలి?',ask:'అడగండి',listen:'వినండి',repeat:'మళ్లీ వినండి',next:'తర్వాతి అడుగు',back:'వెనుకకు',source:'ఈ సమాచారానికి ఆధారం',privacy:'ఆధార్ నంబర్, OTP లేదా PIN ఇక్కడ చెప్పవద్దు.',new:'కొత్త ప్రశ్న',heard:'మీ ప్రశ్న ఇలా వినిపించింది',confirm:'ఇదే నా ప్రశ్న',empty:'ఒక్కో అడుగుతో మరింత నమ్మకం.',emptysub:'వంటకం నుంచి రోజువారీ పనుల వరకు — మీ భాషలో, ఒక్కో అడుగుగా.',step:'అడుగు',of:'/',ready:'సిద్ధంగా ఉన్న మార్గదర్శకాలు',review:'చివరిగా చూసిన తేదీ',notice:'పని చేయడానికి సహాయం. అధికారిక సేవకు ప్రత్యామ్నాయం కాదు.',voiceTitle:'మాట్లాడే ముందు',voiceBody:'మీ మాటలు టెక్స్ట్‌గా మార్చడానికి వాయిస్ సేవకు వెళ్తాయి. ఆధార్ నంబర్, OTP లేదా PIN చెప్పవద్దు. రికార్డింగ్ ఈ యాప్‌లో నిల్వ చేయము.',proceed:'సరే, మాట్లాడతాను',cancel:'వద్దు',open:'అధికారిక సైట్‌కు వెళ్తున్నారు',openBody:'ఆ సైట్‌లోనే అవసరమైన వివరాలు నమోదు చేయండి. తిరిగి స్వయంకు వచ్చి తర్వాతి అడుగు చూడవచ్చు.',finish:'విధానం చూశారు',finishBody:'ఇది మార్గదర్శకం మాత్రమే. అధికారిక పని పూర్తయిందని నిర్ధారణ కాదు.',readAll:'అన్ని అడుగులు చూడండి',close:'మూసివేయండి'},en:{greeting:'Your voice.',together:'Your next step.',sub:'Ask in your own words. Find a clear next step.',speak:'Speak your question',stop:'Stop recording',choose:'What would you like help with?',type:'Or type a question',placeholder:'Example: How do I do Aadhaar KYC for my gas connection?',ask:'Ask Swayam',listen:'Listen',repeat:'Listen again',next:'Next step',back:'Back',source:'Where this information comes from',privacy:'Keep Aadhaar numbers, OTPs and PINs out of this chat.',new:'New question',heard:'Here is what I heard',confirm:'Use this question',empty:'A little guidance. More independence.',emptysub:'From a new recipe to an everyday task — in your language, at your pace.',step:'STEP',of:'OF',ready:'Available guides',review:'Last reviewed',notice:'Independent guidance. Not a government service.',voiceTitle:'Before you speak',voiceBody:'Your audio is sent to a speech service for transcription. Do not say Aadhaar numbers, OTPs or PINs. This app does not store your recording.',proceed:'Continue and speak',cancel:'Cancel',open:'You are leaving Swayam',openBody:'Enter any required private details only on the official service. You can return to Swayam for the next step.',finish:'You have seen the steps',finishBody:'This is guidance, not confirmation that your official task is complete.',readAll:'View all steps',close:'Close'}};
export default function Home(){
 const [lang,setLang]=useState<Language>('te'),[draft,setDraft]=useState(''),[decision,setDecision]=useState<Decision|null>(null),[question,setQuestion]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[recording,setRecording]=useState(false),[transcript,setTranscript]=useState(''),[speaking,setSpeaking]=useState(false),[voiceConsent,setVoiceConsent]=useState(false),[acceptedVoice,setAcceptedVoice]=useState(false),[external,setExternal]=useState(''),[allSteps,setAllSteps]=useState(false),[showTyping,setShowTyping]=useState(false),[status,setStatus]=useState({modelReady:false,transcriptionReady:false,speechReady:false});
 const rec=useRef<Recognizer|null>(null),media=useRef<MediaRecorder|null>(null),stream=useRef<MediaStream|null>(null),audio=useRef<HTMLAudioElement|null>(null),recordTimer=useRef<ReturnType<typeof setTimeout>|null>(null),epoch=useRef(0),answerRef=useRef<HTMLElement|null>(null);
 const c=copy[lang],guide=getGuide(decision?.guideId||''),step=decision?.step||0;
 useEffect(()=>{fetch('/api/status').then(r=>r.json() as Promise<{modelReady:boolean;transcriptionReady:boolean;speechReady:boolean}>).then(setStatus).catch(()=>{});return()=>{rec.current?.stop();media.current?.state==='recording'&&media.current.stop();stream.current?.getTracks().forEach(t=>t.stop());if(recordTimer.current)clearTimeout(recordTimer.current);window.speechSynthesis?.cancel();audio.current?.pause();};},[]);
 function stopSpeech(){epoch.current++;window.speechSynthesis?.cancel();audio.current?.pause();setSpeaking(false);}
 async function ask(text:string){if(busy||!text.trim())return;stopSpeech();setError('');setQuestion(safeAuditText(text));setTranscript('');setDraft('');
  if(privacyReason(text)){setDecision({kind:'blocked',message:c.privacy,reason:'client-privacy',engine:'rules'});return;}
  setBusy(true);try{const r=await fetch('/api/ask',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:text,language:lang,...(guide?{guideId:guide.id,step}:{})})});const data=await r.json() as Decision & {error?:string};if(!r.ok)throw Error(data.error||'Request failed');setDecision(data);setAllSteps(false);setTimeout(()=>answerRef.current?.scrollIntoView({behavior:'smooth',block:'nearest'}),50);}catch{setError(lang==='te'?'ప్రస్తుతం సమాధానం రాలేదు. కింద ఒక పని ఎంచుకుని ప్రయత్నించండి.':'Could not get an answer. Please try again or select a task.');}finally{setBusy(false);}}
 function selectGuide(id:string){stopSpeech();const g=getGuide(id);if(!g)return;setError('');setQuestion(g.title[lang]);setDecision({kind:'guide',guideId:id,step:0,message:g.summary[lang],reason:'selected-guide',engine:'rules'});setAllSteps(false);setTimeout(()=>answerRef.current?.scrollIntoView({behavior:'smooth',block:'start'}),50);}
 function move(n:number){if(!guide)return;stopSpeech();setDecision(d=>d?{...d,step:Math.max(0,Math.min(guide.steps.length-1,n))}:d);}
 async function speak(){if(!guide)return;if(speaking){stopSpeech();return;}setError('');const n=++epoch.current;
  if(status.speechReady){setSpeaking(true);try{const r=await fetch('/api/speak',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({guideId:guide.id,step,language:lang})});if(!r.ok)throw Error();const url=URL.createObjectURL(await r.blob());if(epoch.current!==n){URL.revokeObjectURL(url);return;}audio.current=new Audio(url);audio.current.onended=()=>{setSpeaking(false);URL.revokeObjectURL(url);};audio.current.onerror=()=>{setSpeaking(false);URL.revokeObjectURL(url);};await audio.current.play();return;}catch{setSpeaking(false);}}
  const synth=window.speechSynthesis;if(!synth){setError(lang==='te'?'ఈ పరికరంలో వినిపించే సదుపాయం లేదు.':'Speech playback is unavailable on this device.');return;}
  const voice=synth.getVoices().find(v=>v.lang.toLowerCase().startsWith(lang));if(!voice&&lang==='te'){setError('ఈ పరికరంలో తెలుగు వాయిస్ అందుబాటులో లేదు. తెలుగు వాయిస్ ఉన్న పరికరం ఉపయోగించండి లేదా అడుగులు చదవండి.');return;}
  const u=new SpeechSynthesisUtterance(guide.steps[step][lang]);u.lang=lang==='te'?'te-IN':'en-IN';if(voice)u.voice=voice;u.rate=.85;u.onend=()=>setSpeaking(false);u.onerror=()=>setSpeaking(false);setSpeaking(true);synth.speak(u);
 }
 function handleTranscript(text:string){if(privacyReason(text)){setError(c.privacy);setTranscript('');return;}setTranscript(text);}
 function stopRecording(){rec.current?.stop();if(media.current?.state==='recording')media.current.stop();stream.current?.getTracks().forEach(t=>t.stop());if(recordTimer.current)clearTimeout(recordTimer.current);setRecording(false);}
 async function beginRecording(){setVoiceConsent(false);setAcceptedVoice(true);stopSpeech();setError('');setTranscript('');
  if(status.transcriptionReady&&navigator.mediaDevices?.getUserMedia){try{stream.current=await navigator.mediaDevices.getUserMedia({audio:true});media.current=new MediaRecorder(stream.current);const chunks:BlobPart[]=[];media.current.ondataavailable=e=>chunks.push(e.data);media.current.onstop=async()=>{stream.current?.getTracks().forEach(t=>t.stop());setRecording(false);setBusy(true);try{const blob=new Blob(chunks,{type:media.current?.mimeType||'audio/webm'});const fd=new FormData();fd.append('audio',blob,'question.webm');fd.append('language',lang);const r=await fetch('/api/transcribe',{method:'POST',body:fd});const d=await r.json() as {text:string;error?:string};if(!r.ok)throw Error(d.error);handleTranscript(d.text);}catch{setError(lang==='te'?'వినిపించలేదు. మళ్లీ ప్రయత్నించండి లేదా ఒక పని ఎంచుకోండి.':'Could not transcribe. Try again or select a task.');}finally{setBusy(false);}};media.current.start();setRecording(true);recordTimer.current=setTimeout(stopRecording,25000);return;}catch{setError(lang==='te'?'మైక్రోఫోన్ అనుమతి రాలేదు. ఒక పని ఎంచుకుని కొనసాగండి.':'Microphone access was unavailable. You can select a task instead.');return;}}
  const w=window as SpeechWindow;const Recognition=w.SpeechRecognition||w.webkitSpeechRecognition;if(!Recognition){setError(lang==='te'?'ఈ బ్రౌజర్‌లో మాటలు గుర్తించే సదుపాయం లేదు. మరో బ్రౌజర్ లేదా కింద పనుల ఎంపిక ఉపయోగించండి.':'Speech recognition is unavailable in this browser. Use another browser or select a task below.');return;}
  const r=new Recognition();rec.current=r;r.lang=lang==='te'?'te-IN':'en-IN';r.continuous=false;r.interimResults=false;r.onresult=e=>handleTranscript(e.results[0][0].transcript);r.onerror=()=>{setRecording(false);setError(lang==='te'?'వినిపించలేదు లేదా మైక్రోఫోన్ అనుమతి రాలేదు. మళ్లీ ప్రయత్నించండి.':'Could not hear you or microphone access was denied. Please try again.');};r.onend=()=>setRecording(false);try{r.start();setRecording(true);}catch{setError('Microphone unavailable.');}
 }
 function mic(){if(recording){stopRecording();return;}if(!acceptedVoice)setVoiceConsent(true);else void beginRecording();}
 function reset(){stopRecording();stopSpeech();setDecision(null);setQuestion('');setError('');setTranscript('');setDraft('');}
 useEffect(()=>{const ctx=(document as Document&{modelContext?:{registerTool:(t:unknown,o:unknown)=>Promise<void>}}).modelContext;if(!ctx)return;const life=new AbortController();Promise.resolve(ctx.registerTool({name:'start_swayam_guide',title:'Start an everyday task guide',description:'Open a source-backed guide in the visible interface. Does not complete any official task.',inputSchema:{type:'object',properties:{guideId:{type:'string',enum:GUIDES.map(g=>g.id)}},required:['guideId'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:async(input:unknown)=>{const i=input as {guideId?:unknown};if(!i||Object.keys(i).length!==1||typeof i.guideId!=='string'||!getGuide(i.guideId))throw Error('Choose an available guide.');selectGuide(i.guideId);await new Promise<void>(resolve=>requestAnimationFrame(()=>requestAnimationFrame(()=>resolve())));return {started:i.guideId,officialTaskCompleted:false};}},{signal:life.signal})).catch(()=>{});return()=>life.abort();},[lang]);
 return <main className="swayam-shell" lang={lang}><header className="topbar"><a className="brand" href="/" aria-label="Swayam home"><span className="brand-mark" aria-hidden="true">S</span><span className="brand-name">swayam<span className="brand-native">స్వయం</span></span></a><p className="brand-tagline">{lang==='te'?'మీ మాట. మీ భాష. మీ స్వతంత్రత.':'Your voice. Your language. Your independence.'}</p><div className="header-actions"><span className="india-badge"><span role="img" aria-label="India">🇮🇳</span><span>{lang==='te'?'మనందరి కోసం':'For everyday India'}</span></span><NativeSelect aria-label="Language" value={lang} onChange={e=>{stopRecording();stopSpeech();setLang(e.target.value as Language);setError('');setTranscript('');if(decision?.kind!=='guide')setDecision(null);}}><NativeSelectOption value="te">తెలుగు</NativeSelectOption><NativeSelectOption value="en">English</NativeSelectOption></NativeSelect><Button variant="ghost" onClick={reset} className="reset-button" disabled={busy}><RotateCcw/>{c.new}</Button></div></header>
 <div className="workspace"><aside className="ask-side"><section className="intro"><p className="eyebrow">{lang==='te'?'రోజువారీ పనుల్లో మీ ముందడుగు':'EVERYDAY CONFIDENCE'}</p><h1>{c.greeting}<br/><em>{c.together}</em></h1><p>{c.sub}</p><Button className={'voice-main '+(recording?'is-recording':'')} onClick={mic} disabled={busy}>{recording?<Square/>:<Mic/>}{recording?c.stop:c.speak}</Button><Button variant="ghost" className="type-toggle" onClick={()=>setShowTyping(v=>!v)}><Keyboard/>{c.type}</Button>
 {showTyping&&<form onSubmit={e=>{e.preventDefault();void ask(draft);}} className="ask-form"><Textarea aria-label={c.type} value={draft} onChange={e=>setDraft(e.target.value)} maxLength={1200} placeholder={c.placeholder}/><Button type="submit" disabled={busy||!draft.trim()}><Send/>{c.ask}</Button></form>}
 {transcript&&<div className="transcript"><p>{c.heard}</p><p className="transcript-text">{transcript}</p><div className="inline-actions"><Button onClick={()=>void ask(transcript)}><Check/>{c.confirm}</Button><Button variant="ghost" onClick={()=>setTranscript('')}><X/>{c.cancel}</Button></div></div>}
 {error&&<p className="error-message" role="alert">{error}</p>}
 </section><div className="ask-reassurance"><span aria-hidden="true">✦</span><p>{lang==='te'?'చిన్న ప్రశ్నైనా అడగండి. మీ వేగంలో నేర్చుకోండి.':'Small questions welcome. Take it at your own pace.'}</p></div></aside>
 <section ref={answerRef} className={'answer-side '+(!decision?'empty-answer':'')} aria-live="polite" aria-busy={busy}>{busy?<div className="waiting"><LoaderCircle className="spin"/><p>{lang==='te'?'మీ ప్రశ్న చూస్తున్నాను…':'Looking at your question…'}</p></div>:guide?<><div className="answer-topline"><span><span aria-hidden="true">{topicArt[guide.id]?.emoji} </span>{guide.kind==='story'?(lang==='te'?'కథల సమయం':'STORY TIME'):guide.kind==='recipe'?(lang==='te'?'వంటింట్లో':'IN THE KITCHEN'):(lang==='te'?'ఒక్కో అడుగుగా':'ONE STEP AT A TIME')}</span><Button variant="ghost" size="icon" aria-label={c.close} onClick={reset}><X/></Button></div><h2>{guide.title[lang]}</h2><p className="answer-summary">{guide.summary[lang]}</p><div className="step-track">{guide.steps.map((_,i)=><span className={i<=step?'done':''} key={i}/>)}</div><p className="step-label"><span className="step-number">{String(step+1).padStart(2,'0')}</span><span>{c.step} {step+1} {c.of} {guide.steps.length}</span></p><p className="step-text">{guide.steps[step][lang]}</p><Button variant="outline" className="listen-button" onClick={()=>void speak()}>{speaking?<Square/>:<Volume2/>}{speaking?c.stop:c.listen}</Button><div className="step-nav"><Button variant="ghost" disabled={step===0} onClick={()=>move(step-1)}><ArrowLeft/>{c.back}</Button>{step<guide.steps.length-1?<Button onClick={()=>move(step+1)}>{c.next}<ArrowRight/></Button>:<span className="completed"><Check/>{c.finish}</span>}</div>{step===guide.steps.length-1&&<p className="small-note">{c.finishBody}</p>}<Button variant="ghost" className="all-steps-toggle" onClick={()=>setAllSteps(v=>!v)}>{c.readAll}</Button>{allSteps&&<ol className="all-steps">{guide.steps.map((s,i)=><li key={i}>{s[lang]}</li>)}</ol>}
 {guide.kind==='awareness'&&<p className="awareness-label">{lang==='te'?'సాధారణ న్యాయ అవగాహన • వ్యక్తిగత న్యాయ సలహా కాదు':'General legal awareness • not advice on your particular case'}</p>}<div className="guide-note"><ShieldCheck/><p>{guide.note[lang]}</p></div><Button className="official-button" variant="outline" onClick={()=>setExternal(ACTIONS[guide.actionId].url)}>{ACTIONS[guide.actionId].title[lang]}<ExternalLink/></Button><div className="sources"><h3>{c.source}</h3>{guide.sourceIds.map(id=><a key={id} href={SOURCES[id].url} target="_blank" rel="noopener noreferrer">{SOURCES[id].publisher}<ExternalLink size={14}/></a>)}<p>{c.review}: {guide.reviewed}</p></div></>:decision?<div className="boundary-answer"><ShieldCheck size={36}/><h2>{lang==='te'?'సురక్షితంగా ముందుకు వెళ్దాం':'Let’s take a safe next step'}</h2><p>{decision.message}</p><Button variant="outline" onClick={reset}>{c.new}</Button></div>:<><div className="welcome-heading"><p className="empty-eyebrow">{lang==='te'?'నమస్కారం! స్వయంకు స్వాగతం':'NAMASTE. MAKE YOURSELF AT HOME.'} <span aria-hidden="true">👋</span></p><h2>{c.empty}</h2><p>{c.emptysub}</p></div><img className="family-art" src="/images/swayam-family.png" width="1536" height="1024" alt={lang==='te'?'ఫోన్ ఉపయోగిస్తూ నమ్మకంగా నవ్వుతున్న అమ్మానాన్నల పెన్సిల్ బొమ్మ':'Pencil illustration of two Indian parents confidently using a phone'}/><div className="quick-starts"><span>{lang==='te'?'ఇలా మొదలుపెట్టండి':'A FEW IDEAS TO START'}</span><div><Button variant="outline" onClick={()=>selectGuide('lpg')}>🔥 {lang==='te'?'గ్యాస్ KYC':'Gas KYC'}</Button><Button variant="outline" onClick={()=>selectGuide('chicken-biryani')}>🍲 {lang==='te'?'బిర్యానీ':'Biryani'}</Button><Button variant="outline" onClick={()=>selectGuide('whatsapp')}>💬 {lang==='te'?'వాట్సాప్ స్టేటస్':'WhatsApp status'}</Button></div></div></>}
 </section></div><section className="topics"><div className="topics-heading"><div><p className="section-kicker">{lang==='te'?'మీ రోజులో కొంచెం సహాయం':'A LITTLE HELP FOR YOUR EVERYDAY'}</p><h2>{c.choose}</h2><p className="topics-note">{lang==='te'?'ఒక పని ఎంచుకోండి. కలిసి తెలుసుకుందాం.':'Pick something you’d like to do. We’ll take it one step at a time.'}</p></div><img className="everyday-art" src="/images/swayam-everyday.png" width="1536" height="1024" loading="lazy" alt=""/></div><Tabs defaultValue="all" className="topic-tabs"><TabsList aria-label={lang==='te'?'విషయాలు':'Topic categories'}>{groups.map(g=><TabsTrigger key={g.id} value={g.id}>{g[lang]}</TabsTrigger>)}</TabsList>{groups.map(group=><TabsContent value={group.id} key={group.id}><div className="topic-grid">{topicOrder.map(id=>getGuide(id)).filter(g=>g&&(group.id==='all'||groupOf(g.category)===group.id)).map(g=>{if(!g)return null;const art=topicArt[g.id]||{emoji:'📖',tone:'blue',hint:g.summary};return <Button variant="outline" key={g.id} className={'topic-card tone-'+art.tone+' '+(guide?.id===g.id?'selected':'')} aria-pressed={guide?.id===g.id} onClick={()=>selectGuide(g.id)} disabled={busy}><span className="topic-icon" aria-hidden="true">{art.emoji}</span><span className="topic-copy"><span className="topic-title">{g.title[lang]}</span><span className="topic-hint">{art.hint[lang]}</span></span><ArrowRight size={18}/></Button>;})}</div></TabsContent>)}</Tabs></section><footer><ShieldCheck size={20}/><span>{c.privacy}<br/><small>{c.notice}</small></span><a href="/evaluation">{lang==='te'?'ప్రాజెక్ట్ పరీక్షలు':'Project tests'}</a></footer>
 <Dialog open={voiceConsent} onOpenChange={setVoiceConsent}><DialogContent><DialogHeader><DialogTitle>{c.voiceTitle}</DialogTitle><DialogDescription>{c.voiceBody}</DialogDescription></DialogHeader><DialogFooter><Button variant="outline" onClick={()=>setVoiceConsent(false)}>{c.cancel}</Button><Button onClick={()=>void beginRecording()}>{c.proceed}</Button></DialogFooter></DialogContent></Dialog>
 <Dialog open={!!external} onOpenChange={v=>!v&&setExternal('')}><DialogContent><DialogHeader><DialogTitle>{guide?.kind==='recipe'?(lang==='te'?'వంటకం మూలాన్ని తెరవండి':'Open the recipe source'):c.open}</DialogTitle><DialogDescription>{guide?.kind==='recipe'?(lang==='te'?'కొలతలు, పూర్తి విధానం కోసం అసలు వంటకం పేజీకి వెళ్తున్నారు.':'You are opening the original recipe for quantities and the complete method.'):guide?.kind==='shopping'?(lang==='te'?'మీరు విక్రేత సైట్ తెరుస్తున్నారు. ధర, స్టాక్, డెలివరీ, రిటర్న్ నిబంధనలు అక్కడ నిర్ధారించండి. స్వయం కొనుగోలు చేయదు.':'You are opening a retailer’s website. Check its current price, availability, delivery and returns. Swayam does not place orders.'):c.openBody}</DialogDescription></DialogHeader><p className="external-host">{external?new URL(external).hostname:''}</p><DialogFooter><Button variant="outline" onClick={()=>setExternal('')}>{c.cancel}</Button><Button asChild><a href={external} target="_blank" rel="noopener noreferrer" onClick={()=>setExternal('')}>{lang==='te'?'సైట్ తెరవండి':'Open website'}<ExternalLink/></a></Button></DialogFooter></DialogContent></Dialog>
 </main>;
}
