export type Language = 'te' | 'en';
export type Copy = { te: string; en: string };
export type Guide = { id: string; category: string; title: Copy; summary: Copy; steps: Copy[]; note: Copy; sourceIds: string[]; actionId: string; reviewed: string; kind: 'procedure' | 'entrypoint' | 'recipe' | 'shopping' | 'awareness' | 'story'; keywords: string[] };
export const SOURCES: Record<string,{title:string;url:string;publisher:string;published?:string;checked:string;scope:string}> = {
 lpg:{title:'LPG biometric authentication channels',url:'https://www.pib.gov.in/PressReleaseIframePage.aspx?PRID=2031879',publisher:'Ministry of Petroleum and Natural Gas · PIB',published:'2024-07-09',checked:'2026-09-18',scope:'Provider apps, distributor showrooms, and delivery personnel are listed as authentication channels. This older release does not establish current deadlines or subsidy status.'},
 indane:{title:'IndianOil LPG services',url:'https://iocl.com/lpg-services',publisher:'IndianOil',checked:'2026-09-18',scope:'Official customer portal, distributor locator and customer support entry points.'},
 aadhaar:{title:'UIDAI official services',url:'https://uidai.gov.in/en/',publisher:'UIDAI',checked:'2026-09-18',scope:'Official service entry point. Swayam does not reproduce unverified current app screens, fees, or appointment availability.'},
 digi:{title:'DigiLocker official portal',url:'https://www.digilocker.gov.in/',publisher:'DigiLocker · MeitY',checked:'2026-09-18',scope:'Official entry point only. Detailed current workflow could not be read during this review.'},
 pension:{title:'Jeevan Pramaan service and FAQs',url:'https://jeevanpramaan.gov.in/v2.0/misc/faq',publisher:'Jeevan Pramaan · Government of India',checked:'2026-09-18',scope:'Digital life certificate service and assisted access for eligible pensioners. Confirm scheme eligibility and due date with the pension disbursing agency.'},
 lemon:{title:'Lemon rice recipe',url:'https://www.vegrecipesofindia.com/lemon-rice/',publisher:'Dassana Amit · Veg Recipes of India',published:'2023-02-28',checked:'2026-09-18',scope:'Brief paraphrase of the published method; follow the original recipe for exact quantities.'},
 "biryani":{"title": "Chicken Dum Biryani", "url": "https://ministryofcurry.com/chicken-biryani/", "publisher": "Archana Mundhe · Ministry of Curry", "checked": "2026-09-18", "scope": "Short method overview; use the recipe card for measurements and timings. Ministry of Curry is a recipe publisher, not a government ministry."},
 "food-safety":{"title": "Safe minimum internal temperatures", "url": "https://www.foodsafety.gov/food-safety-charts/safe-minimum-internal-temperatures", "publisher": "FoodSafety.gov", "checked": "2026-09-18", "scope": "Poultry must reach 74°C (165°F), checked with a food thermometer."},
 "whatsapp":{"title": "Create and share a status", "url": "https://faq.whatsapp.com/643144237275579", "publisher": "WhatsApp Help Center", "checked": "2026-09-18", "scope": "Official help search excerpt supports Updates and My status. Detailed platform screens were not fully readable; button positions can differ."},
 "whatsapp-privacy":{"title": "Manage status privacy", "url": "https://faq.whatsapp.com/502161774931737", "publisher": "WhatsApp Help Center", "checked": "2026-09-18", "scope": "Official help excerpt supports Updates > menu > Status privacy on Android. Device layouts may differ."},
 "whatsapp-meta":{"title": "Status audience controls", "url": "https://about.fb.com/news/2023/02/new-whatsapp-status-features/", "publisher": "Meta · WhatsApp", "checked": "2026-09-18", "scope": "Status lasts 24 hours; audience selection controls who sees the update. The 2023 article is not a current screen-by-screen reference."},
 "cookware":{"title": "Cookware collection", "url": "https://myborosil.com/collections/cookware", "publisher": "Borosil · retailer", "checked": "2026-09-18", "scope": "Retailer collection entry point checked. No live stock, price, delivery, safety certification or product endorsement in Swayam."},
 "sarees":{"title": "New arrivals sarees", "url": "https://www.nalli.com/collections/new-arrivals-sarees", "publisher": "Nalli · retailer", "checked": "2026-09-18", "scope": "Retailer new-arrivals collection checked. Products, prices and availability must be checked on the retailer page when buying."},
 "schemes":{"title": "Discover government schemes", "url": "https://www.myscheme.gov.in/", "publisher": "myScheme · MeitY", "checked": "2026-09-18", "scope": "Official discovery portal describes eligibility, benefits, documents and application links. Swayam does not decide eligibility."},
 "policy":{"title": "Government press releases", "url": "https://www.pib.gov.in/", "publisher": "Press Information Bureau", "checked": "2026-09-18", "scope": "Official entry point for government announcements. No specific latest policy or eligibility determination is asserted."},
 "legal-aid":{"title": "Legal aid and application routes", "url": "https://nalsa.gov.in/legal-aid/", "publisher": "NALSA", "checked": "2026-09-18", "scope": "Civil and criminal legal aid, eligibility and district/taluk/state authority routes. Supports access to legal advice, not a finding about land ownership."},
 "legal-help":{"title": "Assistance and legal aid helpline", "url": "https://nalsa.gov.in/womens-assistance/", "publisher": "NALSA", "checked": "2026-09-18", "scope": "Official legal assistance routes and national legal aid helpline 15100."},
 "ganesh":{"title": "Ganesh Chaturthi history and customs", "url": "https://maharashtratourism.gov.in/festivals/ganesh-chaturthi/", "publisher": "Maharashtra Department of Tourism", "checked": "2026-09-18", "scope": "Festival traditions, community celebrations and Tilak’s role in 1893. Not a verified current local event calendar."},
 "ganesh-story":{"title": "Ganesha traditions", "url": "https://en.wikipedia.org/wiki/Ganesha", "publisher": "Wikipedia · cultural reference", "checked": "2026-09-18", "scope": "Secondary reference for one traditional birth narrative. Religious stories vary and are not presented as documented historical events."},
 "festivals":{"title": "Indian festivals and events", "url": "https://utsav.gov.in/", "publisher": "Ministry of Tourism · Utsav", "checked": "2026-09-18", "scope": "Official festival discovery entry point checked via indexed source. No specific local date, booking or event availability is guaranteed."},
};
export const ACTIONS: Record<string,{title:Copy;url:string}> = {
 indane:{title:{en:'Open IndianOil services',te:'IndianOil సేవలు తెరవండి'},url:'https://iocl.com/lpg-services'},
 lpg:{title:{en:'See official LPG options',te:'అధికారిక LPG మార్గాలు చూడండి'},url:SOURCES.lpg.url},
 aadhaar:{title:{en:'Open UIDAI',te:'UIDAI తెరవండి'},url:SOURCES.aadhaar.url},
 digi:{title:{en:'Open DigiLocker',te:'DigiLocker తెరవండి'},url:SOURCES.digi.url},
 pension:{title:{en:'Open Jeevan Pramaan',te:'Jeevan Pramaan తెరవండి'},url:SOURCES.pension.url},
 lemon:{title:{en:'See the full recipe',te:'పూర్తి వంటకం చూడండి'},url:SOURCES.lemon.url},
 "biryani":{"title": {"te": "పూర్తి వంటకం, కొలతలు చూడండి", "en": "Open the full recipe & quantities"}, "url": "https://ministryofcurry.com/chicken-biryani/"},
 "whatsapp":{"title": {"te": "WhatsApp సహాయం తెరవండి", "en": "Open WhatsApp’s help guide"}, "url": "https://faq.whatsapp.com/643144237275579"},
 "cookware":{"title": {"te": "Borosil వంటసామాను చూడండి", "en": "Browse Borosil cookware"}, "url": "https://myborosil.com/collections/cookware"},
 "sarees":{"title": {"te": "Nalli కొత్త చీరలు చూడండి", "en": "Browse Nalli new arrivals"}, "url": "https://www.nalli.com/collections/new-arrivals-sarees"},
 "schemes":{"title": {"te": "myScheme తెరవండి", "en": "Find schemes on myScheme"}, "url": "https://www.myscheme.gov.in/"},
 "legal-aid":{"title": {"te": "NALSA న్యాయ సహాయం చూడండి", "en": "Find legal help with NALSA"}, "url": "https://nalsa.gov.in/legal-aid/"},
 "ganesh":{"title": {"te": "పండుగ చరిత్ర చదవండి", "en": "Read the festival history"}, "url": "https://maharashtratourism.gov.in/festivals/ganesh-chaturthi/"},
 "festivals":{"title": {"te": "Utsavలో పండుగలు చూడండి", "en": "Explore festivals on Utsav"}, "url": "https://utsav.gov.in/"}
};
export const GUIDES: Guide[] = [
 {id:'lpg',category:'services',title:{te:'గ్యాస్ ఆధార్ KYC',en:'LPG Aadhaar KYC'},summary:{te:'మీ గ్యాస్ సంస్థ ద్వారా KYC చేసే మార్గాలు తెలుసుకుందాం. బ్యాంకు సబ్సిడీ లింకింగ్ వేరే పని.',en:'Find your provider’s KYC route. Bank subsidy linking is a separate task.'},steps:[
 {te:'మీ బిల్లు మీద గ్యాస్ సంస్థ పేరు చూడండి: Indane, Bharatgas లేదా HP Gas. ఆధార్ నంబర్ ఇక్కడ చెప్పవద్దు.',en:'Check your bill for the provider: Indane, Bharatgas or HP Gas. Keep your Aadhaar number private.'},
 {te:'కింద ఉన్న అధికారిక సమాచారంలో మీ సంస్థ యాప్ లింక్ ఎంచుకోండి. యాప్‌లో అందుబాటులో ఉన్న KYC సూచనలు అనుసరించండి.',en:'Use your provider’s app link in the official information below. Follow the KYC instructions available in that app.'},
 {te:'యాప్ ఉపయోగించడం కష్టంగా ఉంటే మీ గ్యాస్ డిస్ట్రిబ్యూటర్‌ను సంప్రదించండి. డెలివరీ సిబ్బంది ద్వారా సహాయం అందుతుందో అడగవచ్చు.',en:'If the app is difficult, contact your distributor. You can also ask delivery personnel about assisted authentication.'},
 {te:'KYC పూర్తయిందో మీ సంస్థలోనే నిర్ధారించుకోండి. స్వయం మీ స్థితిని తనిఖీ చేయదు లేదా KYC పూర్తి చేయదు.',en:'Confirm completion with your provider. Swayam cannot check your status or complete your KYC.'}
 ],note:{te:'ఆధారం: జూలై 2024 ప్రకటన. బ్యాంకు-ఆధార్ లేదా సబ్సిడీ లింకింగ్ కోసం బ్యాంకు, గ్యాస్ సంస్థను సంప్రదించండి. ప్రస్తుత గడువు, సబ్సిడీ స్థితి ఇక్కడ నిర్ధారించలేను.',en:'Based on a July 2024 release. Ask your bank and LPG provider about bank-Aadhaar or subsidy linking. Current deadlines, screens and subsidy status are unverified.'},sourceIds:['lpg','indane'],actionId:'lpg',reviewed:'2026-09-18',kind:'procedure',keywords:['gas','గ్యాస్','గ్యాసు','గ్యాస్కి','indane','ఇండేన్','ఇండియన్ గ్యాస్','lpg','bharatgas','hp gas','cylinder','సిలిండర్']},
 {id:'aadhaar',category:'services',title:{te:'ఆధార్ సేవలు',en:'Aadhaar services'},summary:{te:'మార్పులు, కేంద్రాలు, సహాయం కోసం UIDAI అధికారిక సేవలకు వెళ్దాం.',en:'Find the official starting point for updates, centres and support.'},steps:[
 {te:'ఆధార్‌లో ఏ సమాచారం మార్చాలో నిర్ణయించుకోండి. వ్యక్తిగత వివరాలను ఈ చాట్‌లో పంపవద్దు.',en:'Identify what you want to update. Do not send personal identity details into this chat.'},
 {te:'కింద UIDAI లింక్ తెరవండి. మీకు కావలసిన సేవకు ప్రస్తుత అధికారిక సూచనలు చూడండి.',en:'Open UIDAI below and check the current official instructions for your chosen service.'},
 {te:'ఆన్‌లైన్ మార్గం సరిపోకపోతే, UIDAI ద్వారా అధికారిక కేంద్రం లేదా సహాయ మార్గం వెతకండి.',en:'If the online route does not meet your needs, use UIDAI to find an official centre or support route.'}
 ],note:{te:'ఇది అధికారిక సేవకు ప్రారంభ మార్గం మాత్రమే. ప్రస్తుత ఫీజు, అవసరమైన పత్రాలు లేదా మొబైల్ నంబర్ మార్పు స్క్రీన్లను నిర్ధారించలేదు.',en:'Official entry point only. Current fees, document requirements and mobile-update screens have not been verified.'},sourceIds:['aadhaar'],actionId:'aadhaar',reviewed:'2026-09-18',kind:'entrypoint',keywords:['aadhaar','aadhar','ఆధార్','ఆధార','uidai','ఆధారు']},
 {id:'digilocker',category:'documents',title:{te:'డిజిటల్ పత్రాలు',en:'Digital documents'},summary:{te:'DigiLocker అధికారిక సేవను ఎలా చేరుకోవాలో తెలుసుకుందాం.',en:'Find the official DigiLocker service.'},steps:[
 {te:'కింద ఉన్న DigiLocker అధికారిక లింక్ తెరవండి. పత్రాలు ఈ యాప్‌కు అప్‌లోడ్ చేయవద్దు.',en:'Open the official DigiLocker link below. Do not upload identity documents to Swayam.'},
 {te:'లాగిన్, OTP మరియు పత్రాలకు సంబంధించిన సూచనలను DigiLockerలోనే అనుసరించండి.',en:'Follow sign-in, OTP and document instructions inside DigiLocker itself.'},
 {te:'పత్రం కనిపించకపోతే DigiLocker సహాయం లేదా పత్రం ఇచ్చిన సంస్థను సంప్రదించండి.',en:'If your document is unavailable, contact DigiLocker support or the issuing organization.'}
 ],note:{te:'ప్రస్తుత పత్రాల స్క్రీన్లను నేను నిర్ధారించలేకపోయాను. మీ పత్రాలు అందుబాటులో ఉన్నాయని హామీ ఇవ్వలేను.',en:'Current document screens could not be verified. I cannot guarantee that your document is available.'},sourceIds:['digi'],actionId:'digi',reviewed:'2026-09-18',kind:'entrypoint',keywords:['digilocker','డిజిలాకర్','డిజిటల్','document','పత్రం','పత్రాలు','certificate','సర్టిఫికేట్']},
 {id:'pension',category:'services',title:{te:'పెన్షన్ జీవన ధృవపత్రం',en:'Pension life certificate'},summary:{te:'Jeevan Pramaan గురించి మరియు సహాయం పొందే మార్గం గురించి తెలుసుకుందాం.',en:'Understand Jeevan Pramaan and where to get help.'},steps:[
 {te:'మీ పెన్షన్ ఇచ్చే సంస్థ Jeevan Pramaan అంగీకరిస్తుందో, గడువు ఏదో ఆ సంస్థతో నిర్ధారించండి.',en:'Confirm with your pension disbursing agency that it accepts Jeevan Pramaan and ask about your due date.'},
 {te:'అధికారిక సైట్‌లో మీకు అనువైన యాప్ లేదా సమీప Jeevan Pramaan కేంద్రం గురించి చూడండి.',en:'Use the official site to find a suitable application or a nearby Jeevan Pramaan centre.'},
 {te:'అవసరమైన వివరాలు, బయోమెట్రిక్ నిర్ధారణను అధికారిక సేవలోనే పూర్తి చేయండి. వ్యక్తిగత నంబర్లు ఇక్కడ చెప్పవద్దు.',en:'Complete required details and biometric authentication only through the official service. Do not share private numbers here.'},
 {te:'ధృవపత్రం రూపొందితే వచ్చిన నిర్ధారణను భద్రంగా ఉంచండి. స్వయం మీ ధృవపత్రాన్ని సమర్పించదు.',en:'Keep the acknowledgement after successful certificate generation. Swayam does not submit your certificate.'}
 ],note:{te:'అర్హత, గడువు మీ పెన్షన్ సంస్థపై ఆధారపడతాయి. వ్యక్తిగత స్థితిని ఇక్కడ తనిఖీ చేయలేను.',en:'Eligibility and deadlines depend on your pension agency. Personal status cannot be checked here.'},sourceIds:['pension'],actionId:'pension',reviewed:'2026-09-18',kind:'procedure',keywords:['pension','పెన్షన్','జీవన్','jeevan','life certificate','జీవన ధృవ']},
 {id:'lemon-rice',category:'kitchen',title:{te:'నిమ్మకాయ అన్నం',en:'Lemon rice'},summary:{te:'సాధారణ విధానం తెలుసుకుందాం. కొలతల కోసం పూర్తి వంటకం చూడండి.',en:'A brief recipe walkthrough. Open the source for exact quantities.'},steps:[
 {te:'వండిన అన్నం, నిమ్మరసం, నూనె, ఆవాలు, మినప్పప్పు, కరివేపాకు, మిరపకాయలు, పసుపు సిద్ధం చేయండి.',en:'Prepare cooked rice, lemon juice, oil, mustard seeds, urad dal, curry leaves, chillies and turmeric.'},
 {te:'వేరుశెనగలు లేదా జీడిపప్పు వాడితే అలెర్జీ ఉందో ముందుగా చూసుకోండి. అలెర్జీకి అనుకూలమని ఈ వంటకాన్ని హామీ ఇవ్వను.',en:'The source includes peanuts and cashews. Check allergies first; this guide cannot certify the recipe as allergy-safe.'},
 {te:'నూనెలో తాలింపు దినుసులు వేయించి, మంట ఆపిన తరువాత పసుపు కలపండి.',en:'Cook the tempering ingredients in oil; add turmeric after switching off the heat.'},
 {te:'తాలింపును అన్నంలో వేసి నిమ్మరసం, తగిన ఉప్పు కలపండి. పూర్తి విధానం కింద లింక్‌లో ఉంది.',en:'Mix the tempering into the rice, then add lemon juice and salt to taste. See the full source below.'}
 ],note:{te:'ప్రచురిత వంటకం సంక్షిప్త వివరణ. స్వయం వంటకం మూలాన్ని చూపుతుంది; వైద్య లేదా అలెర్జీ భద్రతా నిర్ధారణ ఇవ్వదు.',en:'Brief paraphrase of a published recipe, not medical or allergy-safety certification.'},sourceIds:['lemon'],actionId:'lemon',reviewed:'2026-09-18',kind:'recipe',keywords:['lemon rice','నిమ్మకాయ అన్నం','నిమ్మ అన్నం','nimmakaya annam','nimmakaya pulihora']},
{"id": "chicken-biryani", "category": "kitchen", "title": {"te": "చికెన్ బిర్యానీ", "en": "Chicken biryani"}, "summary": {"te": "సువాసనతో బిర్యానీ: విధానం సంక్షిప్తంగా. కొలతలు పూర్తి వంటకంలో ఉన్నాయి.", "en": "A short dum-biryani walkthrough. Use the full recipe for measurements."}, "steps": [{"te": "చికెన్, బాస్మతి బియ్యం, పెరుగు, మసాలాలు, ఉల్లిపాయలు, పుదీనా సిద్ధం చేసుకోండి. కొలతల కోసం కింద పూర్తి వంటకం తెరవండి.", "en": "Gather chicken, basmati, yogurt, spices, onions and mint. Open the recipe below for quantities."}, {"te": "చికెన్‌కు పెరుగు, మసాలాలు పట్టించి ఫ్రిజ్‌లో ఉంచండి. బియ్యం నానబెట్టండి; ఉల్లిపాయలు బంగారు రంగు వచ్చేలా వేయించండి.", "en": "Refrigerate the chicken in its spiced yogurt marinade. Soak the rice and brown the onions."}, {"te": "మసాలా నీటిలో బియ్యాన్ని దాదాపు ఉడికించి వడకట్టండి. చికెన్‌ను వేరుగా వండటం ప్రారంభించండి.", "en": "Parboil the rice in spiced water and drain. Begin cooking the chicken separately."}, {"te": "చికెన్ మీద బియ్యం, వేయించిన ఉల్లిపాయలు, కుంకుమపువ్వు పాలు పొరలుగా వేయండి. మూతపెట్టి సన్నని మంటపై దమ్ చేయండి. సమయాలకు అసలు వంటకం చూడండి.", "en": "Layer rice over chicken with onions and saffron milk. Cover for low-heat dum cooking; follow the source timings."}, {"te": "వడ్డించే ముందు చికెన్ లోపలి ఉష్ణోగ్రత 74°C చేరిందో ఫుడ్ థర్మామీటర్‌తో చూడండి. రంగు మాత్రమే చూసి నిర్ణయించవద్దు.", "en": "Before serving, use a food thermometer to check chicken reaches 74°C (165°F). Colour alone is not a reliable check."}], "note": {"te": "పెరుగు, పాలు ఉంటాయి. మీ అలెర్జీలకు సరిపోతుందో చూసుకోండి. ఇది సంక్షిప్త విధానం మాత్రమే.", "en": "Contains dairy. Check your allergies. This overview does not replace the full recipe."}, "sourceIds": ["biryani", "food-safety"], "actionId": "biryani", "reviewed": "2026-09-18", "kind": "recipe", "keywords": ["chicken biryani", "chicken biriyani", "chciken biryani", "చికెన్ బిర్యానీ", "చికెన్ బిర్యాని", "కోడి బిర్యానీ"]},
{"id": "whatsapp", "category": "phone", "title": {"te": "వాట్సాప్ స్టేటస్", "en": "WhatsApp status"}, "summary": {"te": "మీ ఫొటోను మీకు నచ్చిన వారితో పంచుకుందాం.", "en": "Share a photo with the people you choose."}, "steps": [{"te": "WhatsApp తెరిచి Updates భాగానికి వెళ్లండి. మీ ఫోన్‌లో దాని పేరు లేదా స్థానం కొంచెం భిన్నంగా ఉండవచ్చు.", "en": "Open WhatsApp and go to Updates. Labels and positions may differ on your phone."}, {"te": "Status దగ్గర My status లేదా జోడించే బటన్‌ను ఎంచుకోండి. మీ గ్యాలరీలోని ఫొటో లేదా వీడియో ఎంచుకోండి.", "en": "Under Status, choose My status or the add control, then select a photo or video from your gallery."}, {"te": "పంచుకునే ముందు ఎవరు చూడాలో Status privacy లేదా audience ఎంపికలో చూసుకోండి. ఆధార్, పాస్‌వర్డ్ లేదా వ్యక్తిగత పత్రాల ఫొటోలు పెట్టవద్దు.", "en": "Before sharing, check Status privacy or the audience control. Keep identity documents and passwords out of your photo."}, {"te": "ఫొటో, ఎవరికి కనిపిస్తుందో మళ్లీ చూసి పంపే బటన్ నొక్కండి. స్టేటస్ సాధారణంగా 24 గంటల తరువాత కనిపించదు. స్వయం మీ తరఫున పోస్ట్ చేయదు.", "en": "Review the photo and audience, then tap the send control. Status disappears after 24 hours. Swayam does not post for you."}], "note": {"te": "Android, iPhone, యాప్ వెర్షన్‌ను బట్టి స్క్రీన్లు మారవచ్చు. కనిపించకపోతే WhatsApp అధికారిక సహాయం చూడండి.", "en": "Screens vary by Android, iPhone and app version. Use WhatsApp’s official help if your screen differs."}, "sourceIds": ["whatsapp", "whatsapp-privacy", "whatsapp-meta"], "actionId": "whatsapp", "reviewed": "2026-09-18", "kind": "procedure", "keywords": ["whatsapp", "whats app", "వాట్సాప్", "వాట్సప్", "వాట్సాపు"]},
{"id": "kitchenware", "category": "shopping", "title": {"te": "వంటింటి సామాను", "en": "Kitchenware & utensils"}, "summary": {"te": "కొత్త కలెక్షన్ చూడండి; కొనేముందు ముఖ్యమైన వివరాలు పోల్చండి.", "en": "Browse the retailer’s current collection and compare before buying."}, "steps": [{"te": "ఏది కావాలో నిర్ణయించుకోండి: కడాయి, పాన్, కుక్కర్ లేదా గిన్నెలు. మీ బడ్జెట్, కావలసిన పరిమాణం గుర్తుపెట్టుకోండి.", "en": "Choose what you need: a kadai, pan, cooker or bowls. Decide your budget and capacity."}, {"te": "కింద Borosil కలెక్షన్ తెరవండి. ఇది ఒక విక్రేత ఎంపిక మాత్రమే; స్వయం తాజా స్టాక్ లేదా ఉత్తమ ధరను నిర్ధారించదు.", "en": "Open the Borosil collection below. It is one browsing option; Swayam does not verify live stock or the best price."}, {"te": "పదార్థం, పరిమాణం, మీ స్టవ్‌కు సరిపోతుందో, నిర్వహణ సూచనలు పోల్చండి. డిజైన్ చూసి మాత్రమే ఎంచుకోవద్దు.", "en": "Compare material, capacity, stove compatibility and care instructions alongside the design."}, {"te": "చెల్లించే ముందు మొత్తం ధర, డెలివరీ, రిటర్న్ నిబంధనలు విక్రేత దగ్గర చూడండి. కొనుగోలు మీరే విక్రేత సైట్‌లో పూర్తి చేయాలి.", "en": "Check total price, delivery and return terms on the retailer’s site. You control any purchase there."}], "note": {"te": "ఇక్కడ ప్రత్యక్ష క్యాటలాగ్ లేదు. తాజా మోడళ్లు, ధరలు, స్టాక్ కోసం విక్రేత పేజీ చూడండి. చిత్రాలు అలంకరణ కోసం మాత్రమే.", "en": "No live catalogue is loaded here. Check the retailer for new models, prices and stock. Artwork is illustrative."}, "sourceIds": ["cookware"], "actionId": "cookware", "reviewed": "2026-09-18", "kind": "shopping", "keywords": ["kitchenware", "kitchen ware", "utensils", "cookware", "వంటసామాను", "వంట సామాను", "వంటింటి", "గిన్నెలు", "వంటపాత్రలు", "vanta samanlu", "ginne"]},
{"id": "sarees", "category": "shopping", "title": {"te": "కొత్త చీరల డిజైన్లు", "en": "Saree designs"}, "summary": {"te": "కొత్త కలెక్షన్‌లో మీకు నచ్చిన చీర కోసం వెతుకుదాం.", "en": "Explore a new-arrivals collection at your own pace."}, "steps": [{"te": "రోజువారీ వాడకానికా, పండుగకా, పెళ్లికా? మీ బడ్జెట్, రంగు, నచ్చిన వస్త్రం ముందుగా అనుకోండి.", "en": "Is it for everyday wear, a festival or a wedding? Choose a budget, colour and fabric preference."}, {"te": "కింద Nalli New Arrivals తెరవండి. అక్కడ ఉన్న తాజా ఫొటోలు, డిజైన్లు చూడండి. ఇవి అమ్మకందారి వివరాలు; స్వయం ఫ్యాషన్ ర్యాంకింగ్ కాదు.", "en": "Open Nalli New Arrivals below for the retailer’s current photos and designs. This is a browsing source, not a trend ranking."}, {"te": "వస్త్రం, చీర పొడవు, బ్లౌజ్ పీస్ ఉందో, సంరక్షణ విధానం చూడండి. ఫొటోలోని రంగు పరికరాన్ని బట్టి మారవచ్చు.", "en": "Check fabric, saree length, blouse inclusion and care. Colours on screen may look different in person."}, {"te": "కొనేముందు ఆ వస్తువు ధర, స్టాక్, డెలివరీ, రిటర్న్ నిబంధనలు నిర్ధారించండి. చెల్లింపు వివరాలు స్వయంలో ఇవ్వవద్దు.", "en": "Check that item’s current price, stock, delivery and returns before buying. Do not enter payment details into Swayam."}], "note": {"te": "విక్రేత కొత్త కలెక్షన్‌కు లింక్ మాత్రమే. నేటి ట్రెండ్లు, ధరలు, స్టాక్‌ను స్వయం ప్రత్యక్షంగా చూడదు.", "en": "A link to a retailer’s new collection. Swayam does not monitor today’s trends, prices or stock."}, "sourceIds": ["sarees"], "actionId": "sarees", "reviewed": "2026-09-18", "kind": "shopping", "keywords": ["saree", "sari design", "చీర", "చీరలు", "cheera", "cheeralu"]},
{"id": "schemes", "category": "services", "title": {"te": "ప్రభుత్వ పథకాలు, విధానాలు", "en": "Government schemes & policies"}, "summary": {"te": "సహాయం, అర్హత, ప్రభుత్వ ప్రకటనలకు అధికారిక మార్గాలు.", "en": "Find official information on benefits, eligibility and announcements."}, "steps": [{"te": "మీ రాష్ట్రం, ఏ సహాయం కావాలో నిర్ణయించుకోండి: విద్య, కుటుంబం, వ్యవసాయం లేదా ఇతర అవసరం. వ్యక్తిగత నంబర్లు ఇక్కడ అవసరం లేదు.", "en": "Start with your state and the help you need: education, family, farming or another area. No private numbers are needed here."}, {"te": "సంక్షేమ పథకాల కోసం కింద myScheme తెరవండి. రాష్ట్రం లేదా విభాగం ద్వారా వెతకండి; అవసరమైన వివరాలను ఆ అధికారిక పోర్టల్‌లోనే ఇవ్వండి.", "en": "For welfare schemes, open myScheme below and browse by state or category. Enter required details only on that official portal."}, {"te": "పథకం పేజీలో ప్రయోజనాలు, అర్హత, పత్రాలు, దరఖాస్తు విధానం చదవండి. గడువు, మీ అర్హతను సంబంధిత శాఖతో నిర్ధారించండి.", "en": "Read benefits, eligibility, documents and the application route. Confirm deadlines and your eligibility with the responsible department."}, {"te": "కొత్త ప్రభుత్వ విధానం లేదా ప్రకటన కోసం కింద PIB ఆధారం తెరవండి. తేదీ, సంబంధిత మంత్రిత్వ శాఖ, అసలు ప్రకటన చూడండి.", "en": "For government policy announcements, use the PIB source below. Check the date, ministry and original release."}], "note": {"te": "ఇది సమాచారాన్ని కనుగొనే మార్గం. అన్ని పథకాలు లేదా తాజా విధానాల సారాంశం కాదు; అర్హత, ఆమోదం హామీ ఇవ్వదు.", "en": "A discovery guide, not a complete or live policy digest. No eligibility or approval is guaranteed."}, "sourceIds": ["schemes", "policy"], "actionId": "schemes", "reviewed": "2026-09-18", "kind": "entrypoint", "keywords": ["government polic", "government scheme", "govt scheme", "govt polic", "ప్రభుత్వ", "పథకం", "పథకాలు", "policy", "policies", "myscheme", "prabhutva"]},
{"id": "land-rights", "category": "legal", "title": {"te": "భూ వివాదం: న్యాయ సహాయం", "en": "Land dispute: legal help"}, "summary": {"te": "భూమి ఆక్రమణ గురించి ఆందోళనగా ఉందా? న్యాయ సహాయం పొందే మొదటి అడుగులు.", "en": "Worried about land encroachment? Start with a safe route to legal help."}, "steps": [{"te": "భూమి ఏ రాష్ట్రం, జిల్లాలో ఉంది? ఇది యాజమాన్య వివాదమా, సరిహద్దు వివాదమా? స్థానిక న్యాయ సహాయ కేంద్రానికి ఈ సాధారణ వివరాలు చెప్పండి; పత్రాలు ఇక్కడ పంపవద్దు.", "en": "Which state and district is the land in? Is the issue ownership or a boundary? Tell your local legal-aid office; do not upload private papers here."}, {"te": "మీ దగ్గర ఉన్న పత్రాలు, సంఘటనల తేదీలు భద్రంగా ఉంచి న్యాయవాదితో చర్చించండి. ఈ యాప్ పత్రాలు పరిశీలించదు, ఎవరి భూమో నిర్ణయించదు.", "en": "Keep your existing documents and a dated account of events for a lawyer. This app cannot examine title or decide ownership."}, {"te": "NALSA 15100కు కాల్ చేయండి లేదా మీ జిల్లా న్యాయ సేవాధికార సంస్థను సంప్రదించండి. న్యాయ సహాయం అర్హత, మీ కేసుకు సరైన మార్గం గురించి అడగండి.", "en": "Call NALSA at 15100 or contact your District Legal Services Authority. Ask about legal-aid eligibility and the appropriate route for your case."}, {"te": "దరఖాస్తు రాయడం కష్టమైతే న్యాయ సహాయ కేంద్రంలో మౌఖికంగా చెప్పి సహాయం అడగవచ్చు. స్వయంగా గొడవకు దిగవద్దు. తక్షణ ప్రమాదమైతే స్థానిక పోలీసు సహాయం పొందండి.", "en": "If writing is difficult, ask the legal-aid office for help making an oral application. Avoid confrontation; seek local police help for immediate danger."}], "note": {"te": "సాధారణ అవగాహన మాత్రమే; వ్యక్తిగత న్యాయ సలహా కాదు. హక్కులు, సరైన చర్య, గడువులు స్థానిక చట్టం, పత్రాలు, వాస్తవాలపై ఆధారపడతాయి. అర్హులైన న్యాయవాదిని సంప్రదించండి.", "en": "General awareness, not individual legal advice. Rights, remedies and deadlines depend on local law, documents and facts. Consult a qualified lawyer."}, "sourceIds": ["legal-aid", "legal-help"], "actionId": "legal-aid", "reviewed": "2026-09-18", "kind": "awareness", "keywords": ["land dispute", "land encroach", "land grab", "kabja", "kabza", "కబ్జా", "భూ వివాద", "భూమి", "ఆక్రమ", "legal rights", "న్యాయ", "mana rights", "land ni", "land documents"]},
{"id": "ganesh", "category": "culture", "title": {"te": "గణేశ చవితి కథ", "en": "Ganesh Chavithi story"}, "summary": {"te": "ఒక సంప్రదాయ కథ, పండుగ వెనుక ఉన్న చరిత్ర తెలుసుకుందాం.", "en": "A traditional story, followed by a little festival history."}, "steps": [{"te": "గణేశ చవితిని వినాయక చవితి అని కూడా అంటారు. హిందూ సంప్రదాయంలో గణేశుని జన్మాన్ని ఈ పండుగలో జరుపుకుంటారు.", "en": "Ganesh Chavithi, also called Vinayaka Chavithi, celebrates Ganesha’s birth in Hindu tradition."}, {"te": "ఒక ప్రసిద్ధ సంప్రదాయ కథలో పార్వతి ఒక బాలుడిని సృష్టించి కాపలాగా ఉంచుతుంది. శివుడితో జరిగిన ఘర్షణ తరువాత బాలుడికి ఏనుగు తలతో మళ్లీ జీవం లభిస్తుంది. కథకు భిన్న రూపాలు ఉన్నాయి.", "en": "In one traditional account, Parvati creates a boy to guard her. After a conflict with Shiva, the boy is restored to life with an elephant’s head. Versions differ."}, {"te": "చరిత్రలోకి వస్తే: 1893లో లోకమాన్య తిలక్ సామూహిక గణేశ ఉత్సవాలను ప్రజలను కలిపే వేదికగా ప్రోత్సహించారు. ఇది సంప్రదాయ కథకు వేరైన చారిత్రక విషయం.", "en": "In documented festival history, Lokmanya Tilak promoted public celebrations in 1893 to bring people together. This is separate from the religious story."}, {"te": "ఇళ్లలో, మండపాల్లో పూజలు, మోదకాలు, సామూహిక వేడుకలు కనిపిస్తాయి. ఆచారాలు ప్రాంతాన్ని బట్టి మారుతాయి. మీ ఇంట్లో పండుగ ఎలా జరుపుకుంటారు?", "en": "Families and communities celebrate with worship, sweets such as modak and gatherings. Customs vary by region. How does your family celebrate?"}], "note": {"te": "మతపరమైన కథను సంప్రదాయంగా, చారిత్రక విషయాన్ని వేరుగా చూపుతున్నాం. నేటి ముహూర్తం లేదా స్థానిక కార్యక్రమాలను నిర్ధారించలేదు.", "en": "Religious narrative is labelled as tradition, separately from historical claims. No current ritual timings or local events are verified."}, "sourceIds": ["ganesh", "ganesh-story"], "actionId": "ganesh", "reviewed": "2026-09-18", "kind": "story", "keywords": ["ganesh", "ganesha", "ganapathi", "ganapati", "vinayaka", "chavithi", "chaturthi", "గణేశ", "గణేష్", "వినాయక", "చవితి"]},
{"id": "festivals", "category": "culture", "title": {"te": "మరిన్ని పండుగలు", "en": "Explore more festivals"}, "summary": {"te": "భారతీయ పండుగలు, ప్రాంతీయ సంప్రదాయాలను తెలుసుకునే మార్గం.", "en": "Find sources for Indian celebrations and regional traditions."}, "steps": [{"te": "ఏ పండుగ గురించి తెలుసుకోవాలో ఎంచుకోండి. ప్రస్తుతం స్వయంలో గణేశ చవితి కథ ఉంది; మిగతా పండుగలకు కింద మూలం చూడండి.", "en": "Choose a festival. Swayam currently has a Ganesh Chavithi story; use the source below for other celebrations."}, {"te": "Utsavలో రాష్ట్రం, పండుగ పేరు ఆధారంగా వెతకండి. ప్రాంతీయ సంప్రదాయం, కథ, చరిత్ర మధ్య తేడా గమనించండి.", "en": "Search Utsav by state and festival. Distinguish regional custom, traditional narrative and recorded history."}, {"te": "కార్యక్రమానికి వెళ్లాలంటే తేదీ, ప్రదేశం, నిర్వహించే సంస్థ వివరాలు మళ్లీ నిర్ధారించండి. పాత పేజీని ఈ ఏడాది కార్యక్రమంగా భావించవద్దు.", "en": "Before attending, confirm the date, place and organizer. An older listing does not establish this year’s event."}], "note": {"te": "ఈ మార్గదర్శకం పండుగల మూలాలను కనుగొనడానికే. అన్ని కథలు ఇంకా యాప్‌లో లేవు.", "en": "This guide helps find festival sources. Not every festival story is available inside the app yet."}, "sourceIds": ["festivals"], "actionId": "festivals", "reviewed": "2026-09-18", "kind": "entrypoint", "keywords": ["festival", "పండుగ", "panduga", "diwali", "దీపావళి", "sankranti", "సంక్రాంతి", "ugadi", "ఉగాది"]}
];
export function getGuide(id:string){return GUIDES.find(g=>g.id===id);}
export function sourceLink(id:string){return SOURCES[id];}
